/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intercambios;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author Francisco Aramburu
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    ArrayList<Expediante>  arre;
    int n;
    
    public Interfaz() {
        initComponents();
        escribe.setText("");
        arre = new ArrayList();
        lee();
    }
    
    public void guardar(){
        try {
            File file = new File("Guardados.txt");
            Scanner input = new Scanner(file);
            try (PrintWriter writer = new PrintWriter(file)) {
                file.delete();
                writer.print("");
            }
            // Escribe Archivo
            int j = arre.size();
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("Guardados.txt"))) {
                for(int i = 0 ;i<j;i++){
                    bw.write(arre.get(i).getCu() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getCreaExp() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getPrimerEnvioSE() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getCorreoAlReciv() + "");
                    bw.write(" ");
                    
                    bw.write(arre.get(i).getSolDeCRNs() + "");
                    bw.write(" ");
                    
                    
                    bw.write(arre.get(i).getCopiaEnvASSySE() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getLleganExpYCrn() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getCrnGenerado() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getEnvioCrnSE() + "");
                    bw.write(" ");
                    bw.write(arre.get(i).getActasGeneradas() + "");
                    bw.write(" " + "\n");
                    bw.write(arre.get(i).getEnvioDepAcad() + "");
                    bw.write(" " + "\n");
                    bw.write(arre.get(i).getRegresoDepAcad() + "");
                    bw.write(" " + "\n");
                    bw.write(arre.get(i).getEntregaDE() + "");
                    bw.write(" " + "\n");
                }
                bw.close();
            } catch (Exception e) {
                throw new ErrorWritingDocumentException();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Expediante.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    
     public void lee(){
        try {
            File file = new File("Guardados.txt");
            try (Scanner input = new Scanner(file)) {
                while(input.hasNext()) {
                    int cuL = Integer.parseInt(input.next());
                    LocalDate creaExpL = LocalDate.parse(input.next());
                    LocalDate primerEnvioSEL = LocalDate.parse(input.next());
                    LocalDate correoAlRecivL = LocalDate.parse(input.next());
                    LocalDate copiaEnvASSySEL = LocalDate.parse(input.next());
                    
                    LocalDate solDeCRNsL = LocalDate.parse(input.next());
                    
                    LocalDate lleganExpYCrnL = LocalDate.parse(input.next());
                    LocalDate crnGeneradoL = LocalDate.parse(input.next());
                    LocalDate envioCrnSEL = LocalDate.parse(input.next());
                    LocalDate actasGeneradasL = LocalDate.parse(input.next());
                    LocalDate envioDepAcadL = LocalDate.parse(input.next());
                    LocalDate regresoDepAcadL = LocalDate.parse(input.next());
                    LocalDate entregaDEL = LocalDate.parse(input.next());
                    Expediante nuevo = new Expediante(cuL, creaExpL, primerEnvioSEL, correoAlRecivL, copiaEnvASSySEL, solDeCRNsL, lleganExpYCrnL, crnGeneradoL, envioCrnSEL, actasGeneradasL, envioDepAcadL, regresoDepAcadL, entregaDEL);
                    arre.add(nuevo);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Expediante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escribe = new java.awt.TextArea();
        cuNuevo = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        cuCons = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        cuAct = new java.awt.TextField();
        btnCrear = new java.awt.Button();
        btnConsExp = new java.awt.Button();
        btnElige = new java.awt.Button();
        btnAct = new java.awt.Button();
        btnConsFechas = new java.awt.Button();
        act3 = new java.awt.Checkbox();
        act4 = new java.awt.Checkbox();
        act5 = new java.awt.Checkbox();
        act6 = new java.awt.Checkbox();
        act7 = new java.awt.Checkbox();
        label9 = new java.awt.Label();
        cons1 = new java.awt.Checkbox();
        cons2 = new java.awt.Checkbox();
        cons3 = new java.awt.Checkbox();
        cons4 = new java.awt.Checkbox();
        btnGuardar = new java.awt.Button();
        act2 = new java.awt.Checkbox();
        act1 = new java.awt.Checkbox();
        act8 = new java.awt.Checkbox();
        act9 = new java.awt.Checkbox();
        act10 = new java.awt.Checkbox();
        btnLimpiar = new java.awt.Button();
        act11 = new java.awt.Checkbox();
        cons5 = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escribe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        escribe.setEditable(false);

        cuNuevo.setName("cuNuevo"); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Nuevo Expediente");

        label2.setText("Clave Única");

        label4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label4.setText("Consulta Expediente");

        label5.setText("Clave Única");

        cuCons.setName("cuCons"); // NOI18N

        label6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label6.setText("Actualiza Expediente");

        label7.setText("Clave Única");

        cuAct.setName("cuAct"); // NOI18N

        btnCrear.setLabel("Crear");
        btnCrear.setName("btnCrear"); // NOI18N
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnConsExp.setLabel("Consultar");
        btnConsExp.setName("btnConsExp"); // NOI18N
        btnConsExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsExpActionPerformed(evt);
            }
        });

        btnElige.setLabel("Elige Expediente");
        btnElige.setName("btnElige"); // NOI18N
        btnElige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEligeActionPerformed(evt);
            }
        });

        btnAct.setEnabled(false);
        btnAct.setLabel("Actualizar");
        btnAct.setName("btnAct"); // NOI18N
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        btnConsFechas.setLabel("Consultar");
        btnConsFechas.setName("btnConsFechas"); // NOI18N
        btnConsFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsFechasActionPerformed(evt);
            }
        });

        act3.setLabel("Copia enviada a SS y SE");
        act3.setName("act3"); // NOI18N

        act4.setLabel("Llegan exp. y CRN's");
        act4.setName("act4"); // NOI18N

        act5.setLabel("CRN's Generados");
        act5.setName("act5"); // NOI18N

        act6.setLabel("Envío CRN´s a SE");
        act6.setName("act6"); // NOI18N

        act7.setLabel("Actas Generadas");
        act7.setName("act7"); // NOI18N

        label9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label9.setText("Consulta Fechas");

        cons1.setLabel("Primer envío a SE");
        cons1.setName("cons1"); // NOI18N

        cons2.setLabel("Espera de CRN's");
        cons2.setName("cons2"); // NOI18N

        cons3.setLabel("Espera para Insc. de Materia");
        cons3.setName("cons3"); // NOI18N

        cons4.setLabel("Calificaciones de Intercambio");
        cons4.setName("cons4"); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(153, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGuardar.setLabel("GUARDAR CAMBIOS");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        act2.setLabel("Correo de Alumno Recibido");
        act2.setName("act2"); // NOI18N

        act1.setLabel("Primer envío a SE");
        act1.setName("act1"); // NOI18N

        act8.setLabel("Envío a Dep. Acad");
        act8.setName("act8"); // NOI18N

        act9.setLabel("Regreso de Dep. Acad.");
        act9.setName("act9"); // NOI18N

        act10.setLabel("Entrega Dir. Esc.");
        act10.setName("act10"); // NOI18N

        btnLimpiar.setLabel("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        act11.setLabel("Solicitud de CRNs");
        act11.setName("act3"); // NOI18N

        cons5.setLabel("Espera Dep. Acad.");
        cons5.setName("cons4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(cuNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cons3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cons4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cons5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnConsExp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cuCons, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnConsFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(act3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(act11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cuAct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnElige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(escribe, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escribe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cuCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cons3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cons4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cons5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(btnConsFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnElige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(act1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(act4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(act10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        int cu;
        Expediante exp;
        btnAct.setEnabled(false);
        boolean ban = false;
        int i =0; 
        int max = arre.size();
        try{
                cu = Integer.parseInt(cuNuevo.getText());
                while(!ban && i<max){
                    if((Integer)(arre.get(i).getCu()) == cu){
                        ban = true;
                        escribe.setText(arre.get(i).toString());
                    }
                    i=i+1;
                }
                if(ban){
                    escribe.setText("El expediente ya existe"); 
                }
                else{
                    exp = new Expediante(cu);
                    escribe.setText("Expediente creado exitosamente.");
                    arre.add(exp);
                }
            }catch(NumberFormatException e){
                escribe.setText("Error, introduzca un número válido.");
            }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        cuNuevo.setText(" ");
        cuAct.setText(" ");
        cuCons.setText(" ");
        cuNuevo.setText("");
        cuAct.setText("");
        cuCons.setText("");
        escribe.setText(" ");
        act1.setState(false);
        act2.setState(false);
        act3.setState(false);
        act4.setState(false);
        act5.setState(false);
        act6.setState(false);
        act7.setState(false);
        act8.setState(false);
        act9.setState(false);
        act10.setState(false);
        act11.setState(false);
        act1.setEnabled(true);
        act2.setEnabled(true);
        act3.setEnabled(true);
        act4.setEnabled(true);
        act5.setEnabled(true);
        act6.setEnabled(true);
        act7.setEnabled(true);
        act8.setEnabled(true);
        act9.setEnabled(true);
        act10.setEnabled(true);
        act11.setEnabled(true);
        cons1.setState(false);
        cons2.setState(false);
        cons3.setState(false);
        cons4.setState(false);  
        btnAct.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
        btnAct.setEnabled(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsExpActionPerformed
        // TODO add your handling code here:
        btnAct.setEnabled(false);
        int cu;
        int i = 0;
        boolean ban = false;
        int max = arre.size();
        try{
            cu = parseInt(cuCons.getText());
            while(!ban && i<max){
                if((Integer)(arre.get(i).getCu()) == cu){
                    ban = true;
                    escribe.setText(arre.get(i).toString());
                }
                i=i+1;
            }
            if(!ban){
               escribe.setText("Expediente Inexistente"); 
            }
        }catch(NumberFormatException e){
                escribe.setText("Error, introduzca un número válido.");
            }        
    }//GEN-LAST:event_btnConsExpActionPerformed

    private void btnEligeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEligeActionPerformed
        // TODO add your handling code here:
        int cu;
        boolean ban = false;
        n = 0;
        int max = arre.size();
        try{
            cu = Integer.parseInt(cuAct.getText());
            while(!ban && n<max){
                if((Integer)(arre.get(n).getCu()) == cu){
                    ban = true;
                    act1.setState(arre.get(n).revisaPrimerEnvioSE());
                    act1.setEnabled(!arre.get(n).revisaPrimerEnvioSE());
                    act2.setState(arre.get(n).revisaCorreoAlReciv());
                    act2.setEnabled(!arre.get(n).revisaCorreoAlReciv());
                    act3.setState(arre.get(n).revisaCopiaEnvASSySE());
                    act3.setEnabled(!arre.get(n).revisaCopiaEnvASSySE());
                    act4.setState(arre.get(n).revisaLleganExpYCrn());
                    act4.setEnabled(!arre.get(n).revisaLleganExpYCrn());
                    act5.setState(arre.get(n).revisaCrnGenerado());
                    act5.setEnabled(!arre.get(n).revisaCrnGenerado());
                    act6.setState(arre.get(n).revisaEnvioCrnSE());
                    act6.setEnabled(!arre.get(n).revisaEnvioCrnSE());
                    act7.setState(arre.get(n).revisaActasGeneradas());
                    act7.setEnabled(!arre.get(n).revisaActasGeneradas());
                    act8.setState(arre.get(n).revisaEnvioDepAcad());
                    act8.setEnabled(!arre.get(n).revisaEnvioDepAcad());
                    act9.setState(arre.get(n).revisaRegresoDepAcad());
                    act9.setEnabled(!arre.get(n).revisaRegresoDepAcad());
                    act10.setState(arre.get(n).revisaEntregaDE());
                    act10.setEnabled(!arre.get(n).revisaEntregaDE());
                    act11.setState(arre.get(n).revisaSolDeCRNs());
                    act11.setEnabled(!arre.get(n).revisaSolDeCRNs());
                    btnAct.setEnabled(true);
                    escribe.setText("Expediente a actualizar con CU = " + arre.get(n).getCu());
                }
                n=n+1;
            }
            if(!ban){
               escribe.setText("Expediente Inexistente"); 
            }
        }catch(NumberFormatException e){
                escribe.setText("Error, introduzca un número válido.");
        }   
    }//GEN-LAST:event_btnEligeActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        // TODO add your handling code here:
        n=n-1;
        if(act1.getState() && act1.isEnabled()){
            arre.get(n).setPrimerEnvioSE(LocalDate.now());
            escribe.setText("Primer Envio SE Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act2.getState() && act2.isEnabled()){
            arre.get(n).setCorreoAlReciv(LocalDate.now());
            escribe.setText("Correo de alumno recibido Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act3.getState() && act3.isEnabled()){
            arre.get(n).setCopiaEnvASSySE(LocalDate.now());
            escribe.setText("copia enviada a SS y SE Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act4.getState() && act4.isEnabled()){
            arre.get(n).setLleganExpYCrn(LocalDate.now());
            escribe.setText("Llegan Exp. y CRN's Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act5.getState() && act5.isEnabled()){
            arre.get(n).setCrnGenerado(LocalDate.now());
            escribe.setText("CRN generado Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act6.getState() && act6.isEnabled()){
            arre.get(n).setEnvioCrnSE(LocalDate.now());
            escribe.setText("Envio CRN a SE Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act7.getState() && act7.isEnabled()){
            arre.get(n).setActasGeneradas(LocalDate.now());
            escribe.setText("Actas Generadas Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act8.getState() && act8.isEnabled()){
            arre.get(n).setEnvioDepAcad(LocalDate.now());
            escribe.setText("Envio Dep. Acad. Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act9.getState() && act9.isEnabled()){
            arre.get(n).setRegresoDepAcad(LocalDate.now());
            escribe.setText("Regreso Dep. Acad. Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        if(act10.getState() && act10.isEnabled()){
            arre.get(n).setEntregaDE(LocalDate.now());
            escribe.setText("Entrega a Dir. Esc. Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        
        if(act11.getState() && act11.isEnabled()){
            arre.get(n).setSolDeCRNs(LocalDate.now());
            escribe.setText("Solicitud de CRNs Actualizado\nCU modificada = "+arre.get(n).getCu());
        }
        btnAct.setEnabled(false);
        act1.setState(false);
        act2.setState(false);
        act3.setState(false);
        act4.setState(false);
        act5.setState(false);
        act6.setState(false);
        act7.setState(false);
        act8.setState(false);
        act9.setState(false);
        act10.setState(false);
        act11.setState(false);
        act1.setEnabled(true);
        act2.setEnabled(true);
        act3.setEnabled(true);
        act4.setEnabled(true);
        act5.setEnabled(true);
        act6.setEnabled(true);
        act7.setEnabled(true);
        act8.setEnabled(true);
        act9.setEnabled(true);
        act10.setEnabled(true);
        act11.setEnabled(true);
        
    }//GEN-LAST:event_btnActActionPerformed

    private void btnConsFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsFechasActionPerformed
        // TODO add your handling code here:
        int k=arre.size();
        int dias;
        String respuesta = "";
        LocalDate control = LocalDate.of(2000, Month.JANUARY, 1);
        LocalDate hoy = LocalDate.now();
        
        if (cons1.getState()){
        }
        else if (cons2.getState()){
            for(int m=0; m<k;m++){
                if(!arre.get(m).getSolDeCRNs().equals(control) && arre.get(m).getLleganExpYCrn().equals(control)){
                    respuesta = respuesta + "\nExpediente: " + arre.get(m).getCu() + "    Días de espera:  " + ChronoUnit.DAYS.between((LocalDate)arre.get(m).getSolDeCRNs(), LocalDate.now());
                }
            }
        }
        else if (cons3.getState()){
            for(int m=0; m<k;m++){
                if(!arre.get(m).getEnvioCrnSE().equals(control) && arre.get(m).getActasGeneradas().equals(control)){
                    respuesta = respuesta + "\nExpediente: " + arre.get(m).getCu() + "    Días de espera:  " + ChronoUnit.DAYS.between((LocalDate)arre.get(m).getEnvioCrnSE(), LocalDate.now());
                }
            }
        }
        else if (cons4.getState()){
        }
        else if (cons5.getState()){
            for(int m=0; m<k;m++){
                if(!arre.get(m).getEnvioDepAcad().equals(control) && arre.get(m).getRegresoDepAcad().equals(control)){
                    respuesta = respuesta + "\nExpediente: " + arre.get(m).getCu() + "    Días de espera:  " + ChronoUnit.DAYS.between((LocalDate)arre.get(m).getEnvioDepAcad(), LocalDate.now());
                }
            }
        }
        if(!respuesta.equals("")){
            escribe.setText(respuesta);
        }
        else{ 
            escribe.setText("No hay datos");
        }
        
        
    }//GEN-LAST:event_btnConsFechasActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox act1;
    private java.awt.Checkbox act10;
    private java.awt.Checkbox act11;
    private java.awt.Checkbox act2;
    private java.awt.Checkbox act3;
    private java.awt.Checkbox act4;
    private java.awt.Checkbox act5;
    private java.awt.Checkbox act6;
    private java.awt.Checkbox act7;
    private java.awt.Checkbox act8;
    private java.awt.Checkbox act9;
    private java.awt.Button btnAct;
    private java.awt.Button btnConsExp;
    private java.awt.Button btnConsFechas;
    private java.awt.Button btnCrear;
    private java.awt.Button btnElige;
    private java.awt.Button btnGuardar;
    private java.awt.Button btnLimpiar;
    private java.awt.Checkbox cons1;
    private java.awt.Checkbox cons2;
    private java.awt.Checkbox cons3;
    private java.awt.Checkbox cons4;
    private java.awt.Checkbox cons5;
    private java.awt.TextField cuAct;
    private java.awt.TextField cuCons;
    private java.awt.TextField cuNuevo;
    public java.awt.TextArea escribe;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
