/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

/**
 *
 * @author FARAMBURA
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uno_uno = new javax.swing.JTextField();
        uno_dos = new javax.swing.JTextField();
        uno_tres = new javax.swing.JTextField();
        dos_uno = new javax.swing.JTextField();
        dos_dos = new javax.swing.JTextField();
        dos_tres = new javax.swing.JTextField();
        tres_uno = new javax.swing.JTextField();
        tres_dos = new javax.swing.JTextField();
        tres_tres = new javax.swing.JTextField();
        uno_cuatro = new javax.swing.JTextField();
        uno_cinco = new javax.swing.JTextField();
        uno_seis = new javax.swing.JTextField();
        dos_cuatro = new javax.swing.JTextField();
        dos_cinco = new javax.swing.JTextField();
        dos_seis = new javax.swing.JTextField();
        tres_cuatro = new javax.swing.JTextField();
        tres_cinco = new javax.swing.JTextField();
        tres_seis = new javax.swing.JTextField();
        uno_siete = new javax.swing.JTextField();
        uno_ocho = new javax.swing.JTextField();
        uno_nueve = new javax.swing.JTextField();
        dos_siete = new javax.swing.JTextField();
        dos_ocho = new javax.swing.JTextField();
        dos_nueve = new javax.swing.JTextField();
        tres_siete = new javax.swing.JTextField();
        tres_ocho = new javax.swing.JTextField();
        tres_nueve = new javax.swing.JTextField();
        cuatro_nueve = new javax.swing.JTextField();
        cinco_siete = new javax.swing.JTextField();
        cinco_ocho = new javax.swing.JTextField();
        cinco_nueve = new javax.swing.JTextField();
        seis_siete = new javax.swing.JTextField();
        seis_ocho = new javax.swing.JTextField();
        seis_nueve = new javax.swing.JTextField();
        seis_tres = new javax.swing.JTextField();
        cuatro_cuatro = new javax.swing.JTextField();
        cuatro_cinco = new javax.swing.JTextField();
        cuatro_seis = new javax.swing.JTextField();
        cinco_cuatro = new javax.swing.JTextField();
        cinco_cinco = new javax.swing.JTextField();
        cinco_seis = new javax.swing.JTextField();
        seis_cuatro = new javax.swing.JTextField();
        seis_cinco = new javax.swing.JTextField();
        seis_seis = new javax.swing.JTextField();
        cuatro_uno = new javax.swing.JTextField();
        cuatro_dos = new javax.swing.JTextField();
        cuatro_tres = new javax.swing.JTextField();
        cinco_uno = new javax.swing.JTextField();
        cinco_dos = new javax.swing.JTextField();
        cinco_tres = new javax.swing.JTextField();
        seis_uno = new javax.swing.JTextField();
        seis_dos = new javax.swing.JTextField();
        cuatro_siete = new javax.swing.JTextField();
        cuatro_ocho = new javax.swing.JTextField();
        siete_nueve = new javax.swing.JTextField();
        ocho_siete = new javax.swing.JTextField();
        ocho_ocho = new javax.swing.JTextField();
        ocho_nueve = new javax.swing.JTextField();
        nueve_siete = new javax.swing.JTextField();
        nueve_ocho = new javax.swing.JTextField();
        nueve_nueve = new javax.swing.JTextField();
        nueve_tres = new javax.swing.JTextField();
        siete_cuatro = new javax.swing.JTextField();
        siete_cinco = new javax.swing.JTextField();
        siete_seis = new javax.swing.JTextField();
        ocho_cuatro = new javax.swing.JTextField();
        ocho_cinco = new javax.swing.JTextField();
        ocho_seis = new javax.swing.JTextField();
        nueve_cuatro = new javax.swing.JTextField();
        nueve_cinco = new javax.swing.JTextField();
        nueve_seis = new javax.swing.JTextField();
        siete_uno = new javax.swing.JTextField();
        siete_dos = new javax.swing.JTextField();
        siete_tres = new javax.swing.JTextField();
        ocho_uno = new javax.swing.JTextField();
        ocho_dos = new javax.swing.JTextField();
        ocho_tres = new javax.swing.JTextField();
        nueve_uno = new javax.swing.JTextField();
        nueve_dos = new javax.swing.JTextField();
        siete_siete = new javax.swing.JTextField();
        siete_ocho = new javax.swing.JTextField();
        resuelve = new javax.swing.JButton();
        respuestas = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uno_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uno_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno_unoActionPerformed(evt);
            }
        });

        uno_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uno_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uno_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dos_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dos_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tres_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tres_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cinco_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cinco_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seis_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seis_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cuatro_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cuatro_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_nueve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_nueve.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_cuatro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_cuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_cinco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_cinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_seis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_seis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ocho_tres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ocho_tres.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_uno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_uno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nueve_dos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nueve_dos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_siete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_siete.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        siete_ocho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        siete_ocho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        resuelve.setText("Resuelve");
        resuelve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resuelveActionPerformed(evt);
            }
        });

        respuestas.setEditable(false);
        respuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestasActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nueve_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ocho_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siete_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nueve_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ocho_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siete_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nueve_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ocho_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(siete_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(seis_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seis_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seis_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cinco_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cuatro_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuatro_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuatro_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(seis_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seis_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seis_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cinco_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cuatro_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuatro_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuatro_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(seis_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seis_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(seis_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cinco_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cinco_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cuatro_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuatro_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cuatro_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tres_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tres_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tres_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dos_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dos_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dos_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(uno_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uno_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uno_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tres_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tres_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tres_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dos_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dos_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dos_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(uno_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uno_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uno_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tres_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tres_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tres_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dos_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dos_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dos_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(uno_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uno_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uno_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resuelve, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(respuestas)
                    .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resuelve))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(uno_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dos_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tres_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(uno_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dos_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tres_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(uno_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dos_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tres_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tres_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cuatro_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cinco_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cinco_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cinco_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(seis_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cuatro_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cinco_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cinco_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cinco_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(seis_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cuatro_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cinco_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cinco_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cinco_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(seis_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(siete_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(siete_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(siete_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ocho_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ocho_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ocho_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nueve_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueve_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueve_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(siete_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(siete_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(siete_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ocho_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ocho_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ocho_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nueve_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueve_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueve_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(siete_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(siete_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(siete_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ocho_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ocho_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ocho_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nueve_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nueve_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nueve_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uno_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno_unoActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_uno_unoActionPerformed

    private void resuelveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resuelveActionPerformed
        // TODO add your handling code here:
       
        try{
            String aux;
            int arre [][] = new int [9][9];
            try{
                arre[0][0] = Integer.parseInt(uno_uno.getText());
            }catch(NumberFormatException e){
                if(!uno_uno.getText().equals("")) 
                    throw new CharacterNotValidException();
                else 
                    arre[0][0] = 0;
            }
            try{
                arre[0][1] = Integer.parseInt(uno_dos.getText());
            }catch(NumberFormatException e){
                if(!uno_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[0][1] = 0;
            }
            try{
                arre[0][2] = Integer.parseInt(uno_tres.getText());        
            }catch(NumberFormatException e){
                if(!uno_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else
                    arre[0][2] = 0;
            }
            try{
                arre[0][3] = Integer.parseInt(uno_cuatro.getText());
            }catch(NumberFormatException e){
                if(!uno_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else
                    arre[0][3] = 0;
            }
            try{
                arre[0][4] = Integer.parseInt(uno_cinco.getText());
            }catch(NumberFormatException e){
                if(!uno_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[0][4] = 0;
            }
            try{
                arre[0][5] = Integer.parseInt(uno_seis.getText());
            }catch(NumberFormatException e){
                if(!uno_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else
                    arre[0][5] = 0;
            }
            try{
                arre[0][6] = Integer.parseInt(uno_siete.getText());
            }catch(NumberFormatException e){
                if(!uno_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[0][6] = 0;
            }
            try{ 
               arre[0][7] = Integer.parseInt(uno_ocho.getText());
            }catch(NumberFormatException e){
                if(!uno_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[0][7] = 0;
            }
            try{
               arre[0][8] = Integer.parseInt(uno_nueve.getText());
            }
            catch(NumberFormatException e){
                if(!uno_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[0][8] = 0;
            }
            //Segundo cubo

            try{
                arre[1][0] = Integer.parseInt(dos_uno.getText());
            }catch(NumberFormatException e){
                if(!dos_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][0] = 0;
            }
            try{
               arre[1][1] = Integer.parseInt(dos_dos.getText());
            }catch(NumberFormatException e){
                if(!dos_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][1] = 0;
            }
            try{
               arre[1][2] = Integer.parseInt(dos_tres.getText());        
            }catch(NumberFormatException e){
                if(!dos_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][2] = 0;
            }
            try{
               arre[1][3] = Integer.parseInt(dos_cuatro.getText());
            }catch(NumberFormatException e){
                if(!dos_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][3] = 0;
            }
            try{
               arre[1][4] = Integer.parseInt(dos_cinco.getText());
            }catch(NumberFormatException e){
                if(!dos_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][4] = 0;
            }
            try{
               arre[1][5] = Integer.parseInt(dos_seis.getText());
            }catch(NumberFormatException e){
                if(!dos_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][5] = 0;
            }
            try{
               arre[1][6] = Integer.parseInt(dos_siete.getText());
            }catch(NumberFormatException e){
                if(!dos_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][6] = 0;
            }
            try{
               arre[1][7] = Integer.parseInt(dos_ocho.getText());
            }catch(NumberFormatException e){
                if(!dos_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][7] = 0;
            }
            try{    
                arre[1][8] = Integer.parseInt(dos_nueve.getText()); 
            }catch(NumberFormatException e){
                if(!dos_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[1][8] = 0;
            }
            //Tercer cubo

            try{
                arre[2][0] = Integer.parseInt(tres_uno.getText());
            }catch(NumberFormatException e){
                if(!tres_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][0] = 0;
            }
            try{
                arre[2][1] = Integer.parseInt(tres_dos.getText());
            }catch(NumberFormatException e){
                if(!tres_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][1] = 0;
            }
            try{
                arre[2][2] = Integer.parseInt(tres_tres.getText());        
            }catch(NumberFormatException e){
                if(!tres_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][2] = 0;
            }
            try{
                arre[2][3] = Integer.parseInt(tres_cuatro.getText());
            }catch(NumberFormatException e){
                if(!tres_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][3] = 0;
            }
            try{
                arre[2][4] = Integer.parseInt(tres_cinco.getText());
            }catch(NumberFormatException e){
                if(!tres_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][4] = 0;
            }
            try{
                arre[2][5] = Integer.parseInt(tres_seis.getText());
            }catch(NumberFormatException e){
                if(!tres_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][5] = 0;
            }
            try{
                arre[2][6] = Integer.parseInt(tres_siete.getText());
            }catch(NumberFormatException e){
                if(!tres_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][6] = 0;
            }
            try{
                arre[2][7] = Integer.parseInt(tres_ocho.getText());
            }catch(NumberFormatException e){
                if(!tres_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[2][7] = 0;
            }
            try{
                arre[2][8] = Integer.parseInt(tres_nueve.getText()); 
            }catch(NumberFormatException e){
                if(!tres_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else
                    arre[2][8] = 0;
            }
            //Cuarto cubo

            try{
                arre[3][0] = Integer.parseInt(cuatro_uno.getText());
            }catch(NumberFormatException e){
                if(!cuatro_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else
                    arre[3][0] = 0;
            }
            try{
                arre[3][1] = Integer.parseInt(cuatro_dos.getText());
            }catch(NumberFormatException e){
                if(!cuatro_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][1] = 0;
            }
            try{
                arre[3][2] = Integer.parseInt(cuatro_tres.getText());        
            }catch(NumberFormatException e){
                if(!cuatro_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][2] = 0;
            }
            try{
                arre[3][3] = Integer.parseInt(cuatro_cuatro.getText());
            }catch(NumberFormatException e){
                if(!cuatro_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][3] = 0;
            }
            try{
                arre[3][4] = Integer.parseInt(cuatro_cinco.getText());
            }catch(NumberFormatException e){
                if(!cuatro_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][4] = 0;
            }
            try{
                arre[3][5] = Integer.parseInt(cuatro_seis.getText());
            }catch(NumberFormatException e){
                if(!cuatro_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][5] = 0;
            }
            try{
                arre[3][6] = Integer.parseInt(cuatro_siete.getText());
            }catch(NumberFormatException e){
                if(!cuatro_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][6] = 0;
            }
            try{
                arre[3][7] = Integer.parseInt(cuatro_ocho.getText());
            }catch(NumberFormatException e){
                if(!cuatro_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][7] = 0;
            }
            try{
                arre[3][8] = Integer.parseInt(cuatro_nueve.getText());
            }catch(NumberFormatException e){
                if(!cuatro_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[3][8] = 0;
            }
            //Quinto cubo 
            try{    
                arre[4][0] = Integer.parseInt(cinco_uno.getText());
            }catch(NumberFormatException e){
                if(!cinco_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][0] = 0;
                }
            try{
                arre[4][1] = Integer.parseInt(cinco_dos.getText());
            }catch(NumberFormatException e){
                if(!cinco_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][1] = 0;
            }
            try{
                arre[4][2] = Integer.parseInt(cinco_tres.getText());
            }catch(NumberFormatException e){
                if(!cinco_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][2] = 0;
            }
            try{
                arre[4][3] = Integer.parseInt(cinco_cuatro.getText());
            }catch(NumberFormatException e){
                if(!cinco_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][3] = 0;
            }
            try{
                arre[4][4] = Integer.parseInt(cinco_cinco.getText());
            }catch(NumberFormatException e){
                if(!cinco_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][4] = 0;
            }
            try{
                arre[4][5] = Integer.parseInt(cinco_seis.getText());
            }catch(NumberFormatException e){
                if(!cinco_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][5] = 0;
            }
            try{
                arre[4][6] = Integer.parseInt(cinco_siete.getText());
            }catch(NumberFormatException e){
                if(!cinco_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[4][6] = 0;
            }
            try{
                arre[4][7] = Integer.parseInt(cinco_ocho.getText());
            }catch(NumberFormatException e){
                if(!cinco_ocho.getText().equals("")) 
                    throw new CharacterNotValidException();
                else 
                    arre[4][7] = 0;
            }
            try{
                arre[4][8] = Integer.parseInt(cinco_nueve.getText()); 
            }catch(NumberFormatException e){
                if(!cinco_nueve.getText().equals("")) 
                    throw new CharacterNotValidException();
                else 
                    arre[4][8] = 0;
            }
            //Sexto cuadro
            try{
                arre[5][0] = Integer.parseInt(seis_uno.getText());
            }catch(NumberFormatException e){
                if(!seis_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][0] = 0;
            }
            try{
                arre[5][1] = Integer.parseInt(seis_dos.getText());
            }catch(NumberFormatException e){
                if(!seis_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][1] = 0;
            }
            try{
                arre[5][2] = Integer.parseInt(seis_tres.getText());
            }catch(NumberFormatException e){
                if(!seis_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][2] = 0;
            }
            try{
                arre[5][3] = Integer.parseInt(seis_cuatro.getText());
            }catch(NumberFormatException e){
                if(!seis_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][3] = 0;
            }
            try{
                arre[5][4] = Integer.parseInt(seis_cinco.getText());
            }catch(NumberFormatException e){
                if(!seis_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][4] = 0;
            }
            try{
                arre[5][5] = Integer.parseInt(seis_seis.getText());
            }catch(NumberFormatException e){
                if(!seis_seis.getText().equals("")) 
                    throw new CharacterNotValidException();
                else 
                    arre[5][5] = 0;
            }
            try{
                arre[5][6] = Integer.parseInt(seis_siete.getText());
            }catch(NumberFormatException e){
                if(!seis_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][6] = 0;
            }
            try{
                arre[5][7] = Integer.parseInt(seis_ocho.getText());
            }catch(NumberFormatException e){
                if(!seis_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][7] = 0;
            }
            try{
                arre[5][8] = Integer.parseInt(seis_nueve.getText());
            }catch(NumberFormatException e){
                if(!seis_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[5][8] = 0;
            }
            //Septimo cuadro
            try{
                arre[6][0] = Integer.parseInt(siete_uno.getText());
            }catch(NumberFormatException e){
                if(!siete_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][0] = 0;
            }
            try{
                arre[6][1] = Integer.parseInt(siete_dos.getText());
            }catch(NumberFormatException e){
                if(!siete_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][1] = 0;
            }
            try{
                arre[6][2] = Integer.parseInt(siete_tres.getText());        
            }catch(NumberFormatException e){
                if(!siete_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][2] = 0;
            }
            try{
                arre[6][3] = Integer.parseInt(siete_cuatro.getText());
            }catch(NumberFormatException e){
                if(!siete_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][3] = 0;
            }
            try{
                arre[6][4] = Integer.parseInt(siete_cinco.getText());
            }catch(NumberFormatException e){
                if(!siete_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][4] = 0;
            }
            try{
                arre[6][5] = Integer.parseInt(siete_seis.getText());
            }catch(NumberFormatException e){
                if(!siete_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][5] = 0;
            }
            try{
                arre[6][6] = Integer.parseInt(siete_siete.getText());
            }catch(NumberFormatException e){
                if(!siete_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][6] = 0;
            }
            try{
                arre[6][7] = Integer.parseInt(siete_ocho.getText());
            }catch(NumberFormatException e){
                if(!siete_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][7] = 0;
            }
            try{
                arre[6][8] = Integer.parseInt(siete_nueve.getText());
            }catch(NumberFormatException e){
                if(!siete_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[6][8] = 0;
            }
            //Octavo cuadro    
            try{
                arre[7][0] = Integer.parseInt(ocho_uno.getText());
            }catch(NumberFormatException e){
                if(!ocho_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][0] = 0;
            }
            try{
                arre[7][1] = Integer.parseInt(ocho_dos.getText());
            }catch(NumberFormatException e){
                if(!ocho_dos.getText().equals("")) 
                    throw new CharacterNotValidException();
                else 
                    arre[7][1] = 0;
            }
            try{
                arre[7][2] = Integer.parseInt(ocho_tres.getText());        
            }catch(NumberFormatException e){
                if(!ocho_tres.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][2] = 0;
            }
            try{
                arre[7][3] = Integer.parseInt(ocho_cuatro.getText());
            }catch(NumberFormatException e){
                if(!ocho_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][3] = 0;
            }
            try{
                arre[7][4] = Integer.parseInt(ocho_cinco.getText());
            }catch(NumberFormatException e){
                if(!ocho_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][4] = 0;
            }
            try{
                arre[7][5] = Integer.parseInt(ocho_seis.getText());
            }catch(NumberFormatException e){
                if(!ocho_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][5] = 0;
            }
            try{
                arre[7][6] = Integer.parseInt(ocho_siete.getText());
            }catch(NumberFormatException e){
                if(!ocho_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][6] = 0;
            }
            try{
                arre[7][7] = Integer.parseInt(ocho_ocho.getText());
            }catch(NumberFormatException e){
                if(!ocho_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][7] = 0;
            }
            try{
                arre[7][8] = Integer.parseInt(ocho_nueve.getText()); 
            }catch(NumberFormatException e){
                if(!ocho_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[7][8] = 0;
            }
            //Noveno cuadro

            try{
                arre[8][0] = Integer.parseInt(nueve_uno.getText());
            }catch(NumberFormatException e){
                if(!nueve_uno.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][0] = 0;
            }
            try{
                arre[8][1] = Integer.parseInt(nueve_dos.getText());
            }catch(NumberFormatException e){
                if(!nueve_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][1] = 0;
            }
            try{
                arre[8][2] = Integer.parseInt(nueve_tres.getText());        
            }catch(NumberFormatException e){
                if(!nueve_dos.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][2] = 0;
            }
            try{
                arre[8][3] = Integer.parseInt(nueve_cuatro.getText());
            }catch(NumberFormatException e){
                if(!nueve_cuatro.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][3] = 0;
            }
            try{
                arre[8][4] = Integer.parseInt(nueve_cinco.getText());
            }catch(NumberFormatException e){
                if(!nueve_cinco.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][4] = 0;
            }
            try{
                arre[8][5] = Integer.parseInt(nueve_seis.getText());
            }catch(NumberFormatException e){
                if(!nueve_seis.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][5] = 0;
            }
            try{
                arre[8][6] = Integer.parseInt(nueve_siete.getText());
            }catch(NumberFormatException e){
                if(!nueve_siete.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][6] = 0;
            }
            try{
                arre[8][7] = Integer.parseInt(nueve_ocho.getText());
            }catch(NumberFormatException e){
                if(!nueve_ocho.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][7] = 0;
            }
            try{
                arre[8][8] = Integer.parseInt(nueve_nueve.getText()); 
            }catch(NumberFormatException e){
                if(!nueve_nueve.getText().equals(""))
                    throw new CharacterNotValidException();
                else 
                    arre[8][8] = 0;
            }
            Sudoku s1 = new Sudoku(arre);
            int arre2[][] = new int [9][9];
            if(s1.revisionInicial()){
                if(s1.resuelve()){
                    arre2 = s1.regresaSudoku();
                    uno_uno.setText(arre2[0][0]+"");
                    uno_dos.setText(arre2[0][1]+"");
                    uno_tres.setText(arre2[0][2]+"");
                    uno_cuatro.setText(arre2[0][3]+"");
                    uno_cinco.setText(arre2[0][4]+"");
                    uno_seis.setText(arre2[0][5]+"");
                    uno_siete.setText(arre2[0][6]+"");
                    uno_ocho.setText(arre2[0][7]+"");
                    uno_nueve.setText(arre2[0][8]+"");
                    dos_uno.setText(arre2[1][0]+"");
                    dos_dos.setText(arre2[1][1]+"");
                    dos_tres.setText(arre2[1][2]+"");
                    dos_cuatro.setText(arre2[1][3]+"");
                    dos_cinco.setText(arre2[1][4]+"");
                    dos_seis.setText(arre2[1][5]+"");
                    dos_siete.setText(arre2[1][6]+"");
                    dos_ocho.setText(arre2[1][7]+"");
                    dos_nueve.setText(arre2[1][8]+"");
                    tres_uno.setText(arre2[2][0]+"");
                    tres_dos.setText(arre2[2][1]+"");
                    tres_tres.setText(arre2[2][2]+"");
                    tres_cuatro.setText(arre2[2][3]+"");
                    tres_cinco.setText(arre2[2][4]+"");
                    tres_seis.setText(arre2[2][5]+"");
                    tres_siete.setText(arre2[2][6]+"");
                    tres_ocho.setText(arre2[2][7]+"");
                    tres_nueve.setText(arre2[2][8]+"");
                    cuatro_uno.setText(arre2[3][0]+"");
                    cuatro_dos.setText(arre2[3][1]+"");
                    cuatro_tres.setText(arre2[3][2]+"");
                    cuatro_cuatro.setText(arre2[3][3]+"");
                    cuatro_cinco.setText(arre2[3][4]+"");
                    cuatro_seis.setText(arre2[3][5]+"");
                    cuatro_siete.setText(arre2[3][6]+"");
                    cuatro_ocho.setText(arre2[3][7]+"");
                    cuatro_nueve.setText(arre2[3][8]+"");
                    cinco_uno.setText(arre2[4][0]+"");
                    cinco_dos.setText(arre2[4][1]+"");
                    cinco_tres.setText(arre2[4][2]+"");
                    cinco_cuatro.setText(arre2[4][3]+"");
                    cinco_cinco.setText(arre2[4][4]+"");
                    cinco_seis.setText(arre2[4][5]+"");
                    cinco_siete.setText(arre2[4][6]+"");
                    cinco_ocho.setText(arre2[4][7]+"");
                    cinco_nueve.setText(arre2[4][8]+"");
                    seis_uno.setText(arre2[5][0]+"");
                    seis_dos.setText(arre2[5][1]+"");
                    seis_tres.setText(arre2[5][2]+"");
                    seis_cuatro.setText(arre2[5][3]+"");
                    seis_cinco.setText(arre2[5][4]+"");
                    seis_seis.setText(arre2[5][5]+"");
                    seis_siete.setText(arre2[5][6]+"");
                    seis_ocho.setText(arre2[5][7]+"");
                    seis_nueve.setText(arre2[5][8]+"");
                    siete_uno.setText(arre2[6][0]+"");
                    siete_dos.setText(arre2[6][1]+"");
                    siete_tres.setText(arre2[6][2]+"");
                    siete_cuatro.setText(arre2[6][3]+"");
                    siete_cinco.setText(arre2[6][4]+"");
                    siete_seis.setText(arre2[6][5]+"");
                    siete_siete.setText(arre2[6][6]+"");
                    siete_ocho.setText(arre2[6][7]+"");
                    siete_nueve.setText(arre2[6][8]+"");
                    ocho_uno.setText(arre2[7][0]+"");
                    ocho_dos.setText(arre2[7][1]+"");
                    ocho_tres.setText(arre2[7][2]+"");
                    ocho_cuatro.setText(arre2[7][3]+"");
                    ocho_cinco.setText(arre2[7][4]+"");
                    ocho_seis.setText(arre2[7][5]+"");
                    ocho_siete.setText(arre2[7][6]+"");
                    ocho_ocho.setText(arre2[7][7]+"");
                    ocho_nueve.setText(arre2[7][8]+"");
                    nueve_uno.setText(arre2[8][0]+"");
                    nueve_dos.setText(arre2[8][1]+"");
                    nueve_tres.setText(arre2[8][2]+"");
                    nueve_cuatro.setText(arre2[8][3]+"");
                    nueve_cinco.setText(arre2[8][4]+"");
                    nueve_seis.setText(arre2[8][5]+"");
                    nueve_siete.setText(arre2[8][6]+"");
                    nueve_ocho.setText(arre2[8][7]+"");
                    nueve_nueve.setText(arre2[8][8]+"");
                    respuestas.setText("Resuelto!");
                }
                else
                    respuestas.setText("Error, no tiene solución");
            }
            else
                respuestas.setText("Error, numeros inválidos");
        }catch(NullPointerException e){
            respuestas.setText("Error, símbolos inválidos");
        }
    }//GEN-LAST:event_resuelveActionPerformed

    private void respuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestasActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:

        uno_uno.setText("");
        uno_dos.setText("");
        uno_tres.setText("");
        uno_cuatro.setText("");
        uno_cinco.setText("");
        uno_seis.setText("");
        uno_siete.setText("");
        uno_ocho.setText("");
        uno_nueve.setText("");
        dos_uno.setText("");
        dos_dos.setText("");
        dos_tres.setText("");
        dos_cuatro.setText("");
        dos_cinco.setText("");
        dos_seis.setText("");
        dos_siete.setText("");
        dos_ocho.setText("");
        dos_nueve.setText("");
        tres_uno.setText("");
        tres_dos.setText("");
        tres_tres.setText("");
        tres_cuatro.setText("");
        tres_cinco.setText("");
        tres_seis.setText("");
        tres_siete.setText("");
        tres_ocho.setText("");
        tres_nueve.setText("");
        cuatro_uno.setText("");
        cuatro_dos.setText("");
        cuatro_tres.setText("");
        cuatro_cuatro.setText("");
        cuatro_cinco.setText("");
        cuatro_seis.setText("");
        cuatro_siete.setText("");
        cuatro_ocho.setText("");
        cuatro_nueve.setText("");
        cinco_uno.setText("");
        cinco_dos.setText("");
        cinco_tres.setText("");
        cinco_cuatro.setText("");
        cinco_cinco.setText("");
        cinco_seis.setText("");
        cinco_siete.setText("");
        cinco_ocho.setText("");
        cinco_nueve.setText("");
        seis_uno.setText("");
        seis_dos.setText("");
        seis_tres.setText("");
        seis_cuatro.setText("");
        seis_cinco.setText("");
        seis_seis.setText("");
        seis_siete.setText("");
        seis_ocho.setText("");
        seis_nueve.setText("");
        siete_uno.setText("");
        siete_dos.setText("");
        siete_tres.setText("");
        siete_cuatro.setText("");
        siete_cinco.setText("");
        siete_seis.setText("");
        siete_siete.setText("");
        siete_ocho.setText("");
        siete_nueve.setText("");
        ocho_uno.setText("");
        ocho_dos.setText("");
        ocho_tres.setText("");
        ocho_cuatro.setText("");
        ocho_cinco.setText("");
        ocho_seis.setText("");
        ocho_siete.setText("");
        ocho_ocho.setText("");
        ocho_nueve.setText("");
        nueve_uno.setText("");
        nueve_dos.setText("");
        nueve_tres.setText("");
        nueve_cuatro.setText("");
        nueve_cinco.setText("");
        nueve_seis.setText("");
        nueve_siete.setText("");
        nueve_ocho.setText("");
        nueve_nueve.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cinco_cinco;
    private javax.swing.JTextField cinco_cuatro;
    private javax.swing.JTextField cinco_dos;
    private javax.swing.JTextField cinco_nueve;
    private javax.swing.JTextField cinco_ocho;
    private javax.swing.JTextField cinco_seis;
    private javax.swing.JTextField cinco_siete;
    private javax.swing.JTextField cinco_tres;
    private javax.swing.JTextField cinco_uno;
    private javax.swing.JTextField cuatro_cinco;
    private javax.swing.JTextField cuatro_cuatro;
    private javax.swing.JTextField cuatro_dos;
    private javax.swing.JTextField cuatro_nueve;
    private javax.swing.JTextField cuatro_ocho;
    private javax.swing.JTextField cuatro_seis;
    private javax.swing.JTextField cuatro_siete;
    private javax.swing.JTextField cuatro_tres;
    private javax.swing.JTextField cuatro_uno;
    private javax.swing.JTextField dos_cinco;
    private javax.swing.JTextField dos_cuatro;
    private javax.swing.JTextField dos_dos;
    private javax.swing.JTextField dos_nueve;
    private javax.swing.JTextField dos_ocho;
    private javax.swing.JTextField dos_seis;
    private javax.swing.JTextField dos_siete;
    private javax.swing.JTextField dos_tres;
    private javax.swing.JTextField dos_uno;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField nueve_cinco;
    private javax.swing.JTextField nueve_cuatro;
    private javax.swing.JTextField nueve_dos;
    private javax.swing.JTextField nueve_nueve;
    private javax.swing.JTextField nueve_ocho;
    private javax.swing.JTextField nueve_seis;
    private javax.swing.JTextField nueve_siete;
    private javax.swing.JTextField nueve_tres;
    private javax.swing.JTextField nueve_uno;
    private javax.swing.JTextField ocho_cinco;
    private javax.swing.JTextField ocho_cuatro;
    private javax.swing.JTextField ocho_dos;
    private javax.swing.JTextField ocho_nueve;
    private javax.swing.JTextField ocho_ocho;
    private javax.swing.JTextField ocho_seis;
    private javax.swing.JTextField ocho_siete;
    private javax.swing.JTextField ocho_tres;
    private javax.swing.JTextField ocho_uno;
    private javax.swing.JTextField respuestas;
    private javax.swing.JButton resuelve;
    private javax.swing.JTextField seis_cinco;
    private javax.swing.JTextField seis_cuatro;
    private javax.swing.JTextField seis_dos;
    private javax.swing.JTextField seis_nueve;
    private javax.swing.JTextField seis_ocho;
    private javax.swing.JTextField seis_seis;
    private javax.swing.JTextField seis_siete;
    private javax.swing.JTextField seis_tres;
    private javax.swing.JTextField seis_uno;
    private javax.swing.JTextField siete_cinco;
    private javax.swing.JTextField siete_cuatro;
    private javax.swing.JTextField siete_dos;
    private javax.swing.JTextField siete_nueve;
    private javax.swing.JTextField siete_ocho;
    private javax.swing.JTextField siete_seis;
    private javax.swing.JTextField siete_siete;
    private javax.swing.JTextField siete_tres;
    private javax.swing.JTextField siete_uno;
    private javax.swing.JTextField tres_cinco;
    private javax.swing.JTextField tres_cuatro;
    private javax.swing.JTextField tres_dos;
    private javax.swing.JTextField tres_nueve;
    private javax.swing.JTextField tres_ocho;
    private javax.swing.JTextField tres_seis;
    private javax.swing.JTextField tres_siete;
    private javax.swing.JTextField tres_tres;
    private javax.swing.JTextField tres_uno;
    private javax.swing.JTextField uno_cinco;
    private javax.swing.JTextField uno_cuatro;
    private javax.swing.JTextField uno_dos;
    private javax.swing.JTextField uno_nueve;
    private javax.swing.JTextField uno_ocho;
    private javax.swing.JTextField uno_seis;
    private javax.swing.JTextField uno_siete;
    private javax.swing.JTextField uno_tres;
    private javax.swing.JTextField uno_uno;
    // End of variables declaration//GEN-END:variables
}
